"""NIR → tscircuit TSX serializer with CLI export for SVG and 3D models."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field

from src.config import Config
from src.nir.migrations import check_version
from src.output.tscircuit_element_map import get_element_type, get_pin_label
from src.output.tscircuit_footprint_map import resolve_footprint
from src.schemas.nir import NIR, PinRef

logger = logging.getLogger(__name__)

_JSX_ELEMENT_NAMES: dict[str, str] = {
    "resistor": "Resistor",
    "capacitor": "Capacitor",
    "inductor": "Inductor",
    "chip": "Chip",
    "diode": "Diode",
    "led": "LED",
    "transistor": "Transistor",
    "connector": "Connector",
    "power_source": "PowerSource",
    "crystal": "Crystal",
    "fuse": "Fuse",
}

_VALUE_PROP_NAMES: dict[str, str] = {
    "resistor": "resistance",
    "capacitor": "capacitance",
    "inductor": "inductance",
}


class TSCircuitOutput(BaseModel):
    tsx_path: Optional[Path] = None
    json_path: Optional[Path] = None
    schematic_svg_path: Optional[Path] = None
    pcb_3d_path: Optional[Path] = None
    unresolved_footprints: list[str] = Field(default_factory=list)
    unresolved_elements: list[str] = Field(default_factory=list)
    cli_error: Optional[str] = None
    success: bool = False


def _format_pin_ref(ref: str, pin: PinRef, element_type: str) -> str:
    pin_label = get_pin_label(element_type, pin.pin_number)
    return f"{ref}.{pin_label}"


def _format_power_net(net_name: str) -> str:
    return f".{net_name}"


def _generate_connections(nir: NIR, component_map: dict[str, str]) -> list[str]:
    lines: list[str] = []
    for net in nir.netlist:
        if net.net_type == "power":
            power_symbol = _format_power_net(net.net_name)
            for pin in net.connections:
                element_type = component_map[pin.ref]
                pin_label = _format_pin_ref(pin.ref, pin, element_type)
                lines.append(f'circuit.connect("{pin_label}", "{power_symbol}")')
        else:
            pins = net.connections
            for i in range(len(pins) - 1):
                a_elem = component_map[pins[i].ref]
                b_elem = component_map[pins[i + 1].ref]
                a = _format_pin_ref(pins[i].ref, pins[i], a_elem)
                b = _format_pin_ref(pins[i + 1].ref, pins[i + 1], b_elem)
                lines.append(f'circuit.connect("{a}", "{b}")')
    return lines


def _generate_tsx(nir: NIR) -> tuple[str, list[str], list[str]]:
    """
    Returns (tsx_content, unresolved_footprints, unresolved_elements)
    """
    unresolved_footprints: list[str] = []
    unresolved_elements: list[str] = []
    component_map: dict[str, str] = {}

    lines = [
        "// Auto-generated by OpenForge tscircuit serializer",
        f"// Design ID: {nir.design_id}",
        f"// Prompt: {nir.prompt}",
        "",
        "import { Circuit, Resistor, Capacitor, Inductor,",
        "         Chip, Diode, LED, Transistor, Connector,",
        "         PowerSource, Crystal, Fuse } from \"@tscircuit/core\"",
        "",
        "export const circuit = new Circuit()",
        "",
        "// ── Components ──────────────────────────────────────",
    ]

    for component in nir.components:
        element_type, elem_needs_review = get_element_type(component.component_type)
        footprint, fp_needs_review = resolve_footprint(
            component.footprint, component.component_type
        )

        component_map[component.ref] = element_type

        if elem_needs_review:
            unresolved_elements.append(
                f"{component.ref} ({component.component_type})"
            )
        if fp_needs_review:
            unresolved_footprints.append(
                f"{component.ref} ({component.footprint})"
            )

        props = f'name="{component.ref}" footprint="{footprint}"'
        if component.value:
            value_prop = _VALUE_PROP_NAMES.get(element_type, "value")
            props += f' {value_prop}="{component.value}"'

        jsx_elem = _JSX_ELEMENT_NAMES.get(element_type, element_type.capitalize())
        comment = f"  // {component.component_id}"
        lines.append(f"circuit.add(<{jsx_elem} {props} />){comment}")

    lines.append("")
    lines.append("// ── Connections ─────────────────────────────────────")
    lines.extend(_generate_connections(nir, component_map))

    lines.append("")
    lines.append("// ── Placement Constraints ───────────────────────────")
    for constraint in nir.placement_constraints:
        if constraint.max_distance_mm is not None:
            lines.append(
                f'circuit.place("{constraint.ref}", '
                f'{{ near: "{constraint.relative_to}", '
                f'maxDistance: "{constraint.max_distance_mm}mm" }})'
            )

    for item in unresolved_footprints:
        logger.warning("Unresolved tscircuit footprint: %s", item)
    for item in unresolved_elements:
        logger.warning("Unresolved tscircuit element type: %s", item)

    return "\n".join(lines), unresolved_footprints, unresolved_elements


def _run_cli(
    tsx_path: Path,
    output_dir: Path,
    fmt: str,
    suffix: str,
) -> tuple[Optional[Path], Optional[str]]:
    """
    Run tscircuit CLI export command.
    Returns (output_path, error_message).
    error_message is None on success.
    """
    out_path = output_dir / f"{tsx_path.stem}{suffix}"
    try:
        result = subprocess.run(
            [
                "npx",
                "@tscircuit/cli",
                "export",
                "--format",
                fmt,
                "--output",
                str(out_path),
                str(tsx_path),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            return None, result.stderr
        return out_path, None
    except FileNotFoundError:
        return None, "tscircuit CLI not found. Run: npm install -g @tscircuit/cli"
    except subprocess.TimeoutExpired:
        return None, "tscircuit CLI timed out after 120 seconds"


def serialize_to_tscircuit(
    nir: NIR,
    output_dir: Path,
    config: Config,
) -> TSCircuitOutput:
    """
    Convert NIR to tscircuit format.
    Calls tscircuit CLI to produce SVG schematic and 3D GLB model.
    Never raises — returns TSCircuitOutput with error flags on failure.

    Raises ValueError if NIR schema version does not match the serializer.
    """
    check_version(nir)

    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        tsx_content, unresolved_fp, unresolved_elem = _generate_tsx(nir)
        tsx_path = output_dir / f"{nir.design_id}.tsx"
        tsx_path.write_text(tsx_content, encoding="utf-8")

        svg_path, svg_err = _run_cli(tsx_path, output_dir, "svg", "_schematic.svg")
        glb_path, glb_err = _run_cli(tsx_path, output_dir, "3d", "_pcb_3d.glb")
        cli_error = svg_err or glb_err

        return TSCircuitOutput(
            tsx_path=tsx_path,
            schematic_svg_path=svg_path,
            pcb_3d_path=glb_path,
            unresolved_footprints=unresolved_fp,
            unresolved_elements=unresolved_elem,
            cli_error=cli_error,
            success=True,
        )
    except Exception as exc:
        logger.error("tscircuit serialization failed: %s", exc)
        return TSCircuitOutput(cli_error=str(exc))
